import type { Post } from './types'

export const post: Post = {
  slug: 'national-headlines-tri-valley-summer',
  title: `What the National Headlines *Get Wrong* About the Tri-Valley This Summer`,
  category: 'Market Update',
  date: '2026-06-26',
  excerpt: `The most useful thing a national real estate economist said this summer was a warning against listening to national real estate economists.`,
  body: [
    `Selma Hepp, Chief Economist at Cotality (formerly CoreLogic), spent a recent interview on *Real Estate This Week* walking through the summer 2026 market — and her central point was that there isn’t one. There is no national housing story anymore. The numbers that make headlines are averages of dozens of local markets moving in different directions, and a buyer or seller in Pleasanton is poorly served by any of them.`,
    `So let me do the translation. Here’s what Hepp’s national read actually says, and what it means a few minutes off the 580.`,
    { h: 'The national picture: cooler, but not cheaper' },
    `Hepp’s summary of the country is a market that has cooled without correcting. Transaction volume is subdued. A mid-year jump in mortgage rates — tied to oil prices and overseas conflict — gave buyers a fresh reason to hesitate, but demand hasn’t broken; people who’ve been waiting are stepping back in. In much of the country that adds up to less competition, fewer bidding wars, and more room to negotiate than the frenzy years.`,
    `What it does *not* add up to is lower prices. By Cotality’s numbers, home prices nationally are up roughly 50% from the start of the pandemic, and as much as 90% in some markets. The typical mortgage payment runs about 63% higher than it did in 2019 for the same median home. The affordability math has changed permanently, even where the bidding wars have stopped.`,
    `That’s the national story. It mostly doesn’t describe us.`,
    { h: 'Why the Tri-Valley is the exception, not the example' },
    `The “buyers finally have leverage” narrative depends on inventory. Where Hepp sees it loosening, it’s because of new construction, investors and second-home owners listing, or markets that simply ran out of population growth to support demand. The Tri-Valley has almost none of those release valves.`,
    `The local numbers tell a different story than the national one:`,
    { list: [
      `The Pleasanton median sits around **$1.5 million**.`,
      `Inventory is roughly **1.4 months of supply** — a balanced market is 5 to 6 months. We are nowhere near balanced.`,
      `Well-priced homes are still going under contract in about **two to three weeks**, at close to **99% of list**.`,
      `Alameda County remains among the **tightest** inventory markets in the entire state.`,
    ] },
    `So when you read that buyers nationally have the upper hand, set it down before you apply it here. A reasonable Pleasanton listing in good condition is not sitting. The leverage Hepp describes belongs to buyers in markets that built a lot of houses or attracted a lot of investors. The Tri-Valley did neither.`,
    `One honest footnote, since it matters: you’ll see year-over-year price figures for Pleasanton ranging from down 3% to down 17% depending on the source. Don’t trust any single one. Those swings are mostly *mix* — whether a given month happened to close more luxury homes in Ruby Hill or more mid-market homes in Birdland — not the value of your specific house moving. Your home’s number comes from a comparative analysis of homes like yours, not a citywide median.`,
    { h: 'For buyers: the rate is the tradeoff, not the price' },
    `Hepp’s advice to buyers is unsentimental, and I agree with it. Waiting for prices to fall is, historically, waiting for something that rarely arrives — and when rates do eventually ease, the competition that’s currently sitting on the sidelines comes back and pushes prices the other way.`,
    `The old line still holds: you can refinance a rate, but you can’t refinance a price. If you buy a home you can carry today and rates improve in a year or two, you refinance. If you wait for prices to drop in a low-supply market like ours, you’re more likely to watch them rise while paying someone else’s mortgage in rent.`,
    `For Tri-Valley buyers specifically, that means the real question isn’t *whether* this is a good moment — it’s whether you’re financially positioned to buy a home you can hold, in a market that has not offered, and likely will not offer, a discount for patience.`,
    { h: 'For sellers: the era of the easy sale is over, but your equity isn’t' },
    `The “sign in the yard, sold by dinner” market is gone, even here. Hepp describes sellers who now have to price carefully, who watch homes get listed, pulled, and relisted lower during price discovery, and who are offering concessions again — help with closing costs, repairs, inspection items. That discipline applies in the Tri-Valley too. Overprice into this market and even a tight-inventory neighborhood will let your listing go stale.`,
    `But there’s a second half to the seller story that’s easy to miss, and it’s the strongest card on the table. Hepp’s framing: of the roughly $45 trillion in U.S. residential value, about $35 trillion belongs to homeowners themselves — not banks. The average mortgaged owner holds over $300,000 in equity.`,
    `In the Tri-Valley, where the price base is roughly double the national median, owners who bought five to seven years ago are very likely sitting well above that national average. That equity is the real lever. It’s what funds the move up, the downsize with cash left over, the relocation closer to family or grandkids. In a slower market, the question for most sellers stops being “is the market hot” and becomes “what does my reason for moving need, and what does my equity make possible?” Those are usually life decisions — retirement, a job, family — not market-timing calls. The equity is what lets you make them on your terms.`,
    { h: 'The honest bottom line' },
    `Hepp’s national verdict was “as good a time as any” to buy, and “it depends on why you’re selling.” Locally, I’d put it more plainly: the Tri-Valley is not the buyer’s market the national coverage describes, and it isn’t likely to become one soon. For buyers, that argues against waiting for a discount that isn’t coming. For sellers, it argues for pricing with discipline and thinking hard about what your equity is for.`,
    { cta: `If you want to know what any of this means for your specific home or your specific search — not the citywide median, but your block — call or text me. That’s a conversation worth having before the summer’s over.` },
    { disclaimer: 'I am not a financial advisor. Please consult your CPA or trusted financial strategist before making any financial decisions.' },
    { disclaimer: 'Market commentary draws on Selma Hepp, Chief Economist at Cotality, on Real Estate This Week with Stephen Gasque (June 2026). Local figures reflect recent Pleasanton/Tri-Valley market data and are directional; current conditions for a specific property or neighborhood vary.' },
  ],
}
