import type { Post } from './types'

export const post: Post = {
  slug: 'proximity-premium-san-jose',
  title: `The Proximity Premium: How the AI Boom Is *Quietly* Redrawing San Jose’s Map`,
  category: 'Market Update',
  date: '2026-05-29',
  excerpt: `When people talk about the AI boom and Bay Area real estate, they point to Cupertino, Palo Alto, Los Altos. But the most revealing story isn’t in those five zip codes — it’s in the city next door, the biggest one in the Bay Area. San Jose is where you can actually watch AI money move. Not in headlines, but block by block.`,
  body: [
    { h: 'The Headline Number Is Hiding the City' },
    `Look at the top line and the market reads like it’s cooling. The median sale price in San Jose was about $1.49M last month — up only a few percent from a year ago, and barely budging month to month (Redfin, Houzeo). Borrowing costs aren’t helping: Freddie Mac’s 30-year fixed climbed to 6.53% as of May 28, its third straight weekly uptick.`,
    `The cooling signals are real, too. Inventory is up sharply — more than 60% year over year — homes with price reductions jumped from about 18% to 25%, and the share selling over asking fell from roughly 74% to 64% (Houzeo).`,
    `But San Jose is a city of over a million people and dozens of distinct neighborhoods. A single median can’t describe it any more than one temperature describes a whole season. Underneath that number, the city is splitting into very different stories — and the dividing line, increasingly, is distance to a chip campus.`,
    { h: 'The Proximity Premium Is Real' },
    `Nvidia’s headquarters sits in Santa Clara, right against San Jose’s northern edge, and the AI infrastructure build-out is now landing inside the city itself. A Nvidia-leased building at 300 Holger Way in North San Jose is slated to convert into a major AI data center, with work starting late this year (GovTech).`,
    `That gravity shows up in demand. North San Jose, Berryessa, and the neighborhoods with a short, predictable commute to that corridor draw buyers who work in AI but won’t — or can’t — write a Cupertino number. They want the proximity without the peninsula premium, and San Jose is the obvious trade. In these pockets, well-priced homes still see real competition even as the citywide average drifts sideways.`,
    `This is the AI boom’s second ripple. The first hit the elite zips. The second is landing here.`,
    { h: 'San Jose as the Landing Zone' },
    `There’s a second kind of buyer reshaping the city: the upgrader priced out of the peninsula entirely.`,
    `The family that wanted Los Altos or Cupertino, ran the math at 6.5%, and decided their dollar goes further in Willow Glen, the Rose Garden, Almaden, or Evergreen. The numbers show how wide that ladder is — West San Jose single-family homes run a median near $3.4M and Willow Glen around $2.2M, while townhomes citywide sit closer to $1.3M (Redfin). These established, school-anchored neighborhoods are absorbing demand that used to flow north and west — and that puts a floor under San Jose’s strongest pockets the citywide median completely hides.`,
    `If you’re selling in one of these areas, your buyer pool is wider than the headlines suggest. If you’re buying, you’re competing with people who already lost a bidding war somewhere more expensive — and they’re motivated.`,
    { h: 'The Downtown Exception' },
    `Now the contrarian part. Not every corner of San Jose is riding this wave.`,
    `Downtown condos remain the city’s soft spot, with one-bedroom units around $545K and two-bedrooms near $715K (Redfin). The big office and campus plans meant to anchor the core have moved slower than promised, hybrid work thinned the weekday crowd, and HOA dues plus today’s rates make the monthly math hard. Many of these units sit longer and negotiate more.`,
    `For the right buyer — someone who wants walkability, isn’t betting on a quick flip, and can look past the headlines — this is one of the few places in San Jose where you still have genuine leverage. The same AI era lifting North San Jose is leaving parts of downtown on sale.`,
    { h: 'Knowing Which San Jose You’re Standing In' },
    `The useful question in 2026 isn’t “how’s the San Jose market?” It’s “which San Jose?”`,
    `The proximity corridor, the family-neighborhood landing zone, and the downtown core are three different markets wearing one city’s name — and each demands a different playbook on price, contingencies, and how aggressive your offer needs to be. Bring the wrong read to the wrong neighborhood and you either overpay or walk away from a deal you should have won.`,
    `That read — which San Jose, which strategy — is the whole game right now. And it’s exactly what a citywide median will never tell you.`,
    { cta: `If you want to know which San Jose your target neighborhood actually belongs to — and what your offer needs to look like to win there — call or text me, and I’ll walk you through the real numbers for your specific search.` },
    { disclaimer: 'I am not a financial advisor. Please consult your CPA or trusted financial strategist before making any financial decisions.' },
    { sources: [
      { t: 'Redfin — San Jose housing market', href: 'https://www.redfin.com/city/17420/CA/San-Jose/housing-market' },
      { t: 'Houzeo — San Jose 2026 market trends', href: 'https://www.houzeo.com/housing-market/california/san-jose' },
      { t: 'Freddie Mac PMMS', href: 'https://www.freddiemac.com/pmms' },
      { t: 'GovTech — Nvidia-leased San Jose building to become AI data center', href: 'https://insider.govtech.com/california/news/nvidia-leased-san-jose-building-poised-to-become-major-ai-data-center' },
    ] },
  ],
}
